services:
  db:
    image: postgres:17.5-bookworm
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    command:
      - postgres
    networks:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 3052:8080
    networks:
      - postgres

  backend:
    container_name: categorize-backend
    # volumes:
    #   - backend:/app
    build:
      context: ./fastapi-categorise-backend
    ports:
      - "3051:80"
    develop:
      watch:
        - action: sync
          path: ./fastapi-categorise-backend
          target: /app
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock
  frontend:
    container_name: categorize-frontend
    restart: always
    build:
      context: ./vue-categorise-frontend
    volumes:
      - frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - DOCKER=true
    develop:
      watch:
        - action: sync
          path: ./vue-categorise-frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
volumes:
  frontend:
    driver: local
  backend:
    driver: local
  pgdata:
    driver: local
