services:
  db:
    image: postgres:17.5-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    command:
      - postgres
    networks:
      - postgres
    env_file:
      - .env

  adminer:
    image: adminer:5.3.0
    restart: always
    ports:
      - 3052:8080
    networks:
      - postgres

  backend:
    container_name: categorize-backend
    # volumes:
    #   - backend:/app
    build:
      context: ./fastapi-categorise-backend
    ports:
      - "3051:80"
    develop:
      watch:
        - action: sync
          path: ./fastapi-categorise-backend
          target: /app
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock
    networks:
      - app
      - postgres
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: categorize-frontend
    restart: always
    build:
      context: ./vue-categorise-frontend
    ports:
      - "3050:5173"
    environment:
      - NODE_ENV=development
      - DOCKER=true
    develop:
      watch:
        - action: sync
          path: ./vue-categorise-frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - app
    depends_on:
      - backend

volumes:
  backend:
    driver: local
  pgdata:
    driver: local

networks:
  postgres:
  app:
