services:
  db:
    image: postgres:17.5-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "3053:5432"
    command:
      - postgres
    networks:
      - postgres
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer:5.3.0
    restart: always
    ports:
      - 3052:8080
    networks:
      - postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
